version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    image: postmodern-server:latest
    container_name: postmodern-server
    restart: unless-stopped
